// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgresql

import (
	"database/sql"
	"time"
)

type Transactions struct {
	ID                     int32
	TransactionRef         string
	TransactionType        string
	TransactionTimestamp   time.Time
	Amount                 string
	Secretkey              string
	TransactionStatus      string
	TransactionDescription string
	Balance                string
	CreatedTime            sql.NullTime
	ModifiedTime           sql.NullTime
	WalletID               sql.NullInt32
}

type Wallet struct {
	ID           int32
	WalletNumber string
	IsActive     string
	FirstName    sql.NullString
	LastName     sql.NullString
	Email        string
	Secretkey    string
	Bvn          string
	Dob          sql.NullTime
	Currency     string
	CreatedTime  sql.NullTime
	ModifiedTime sql.NullTime
}
